title: Cosmetify
email: cosmetify@live.com
encoding: utf-8
description: Nothing too special yet
url: https://cosmetify.net
twitter_username: cosmetify
github_username: cosmetify
timezone: America/New_York
paginate: 5

# Build settings
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock